version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise:10.2.2
    container_name: grafana
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 5s
    ports:
     - '3000:3000'
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
  pdfgen:
    build: pdfgen
    image: test
    container_name: pdfgen
    restart: on-failure
    depends_on:
      grafana:
        condition: service_healthy
    volumes:
      - pdfvol:/tmp/pdf
volumes:
  pdfvol:
    driver: local
    driver_opts:
      type: none
      device: /tmp/pdf
      o: bind
